FROM alpine:3.15
RUN apk --no-cache add \
    wget \
    curl \
    php \
    php-curl \
    php-iconv \
    php-json \
    php-mbstring \
    php-openssl \
    php-phar \
    php-dom \
    php-xml \
    php-ctype \
    php-tokenizer \
    php-xmlwriter \
    php-session \
    bash \
    git

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY . /usr/src/application/backend/
WORKDIR /usr/src/application/backend/
RUN composer install
CMD [ "composer", "run-backend" ]