tasks:
  - init: Install Tilt
  - command: curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash

ports:
  - port: 5000
    onOpen: ignore
  - port: 10350
    onOpen: open-browser
  - port: 9200
    onOpen: open-preview
  - port: 9300
    onOpen: ignore
  - port: 9600
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker


github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false