version: "2.4"

services:
  application:
    container_name: node-express-app
    build:
      dockerfile: Dockerfile
      context: ./application
    environment:
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - OTEL_SERVICE_NAME=otel-trinity
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "8080:8080"

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.70.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./logs:/logs
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317"        # OTLP gRPC receiver
      - "4318"        # OTLP http receiver
      - "55670:55679" # zpages extension
      - "9411" # zipkin
    environment:
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
