receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otelcol'
          scrape_interval: 30s
          static_configs:
            - targets: ['0.0.0.0:8888']
          metric_relabel_configs:
            - source_labels: [__name__]
              regex: '.*grpc_io.*'
              action: drop
  filelog:
    include: [ /logs/collector-debug.log ]
    operators:
      - type: json_parser
        parse_from: body

processors:
  batch:
  memory_limiter:
    check_interval: 5s
    limit_mib: 4000
    spike_limit_mib: 500
  resource:
    attributes:
      - key: env
        value: local
        action: insert
      - key: usage
        value: otel-collector-workshop
        action: insert

exporters:
  otlp/logs:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": ${HONEYCOMB_API_KEY}
      "x-honeycomb-dataset": 'o11y-workshop'

  otlp/metrics:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": ${HONEYCOMB_API_KEY}
      "x-honeycomb-dataset": 'o11y-workshop'

  otlp/traces:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": ${HONEYCOMB_API_KEY}
      "x-honeycomb-dataset": 'o11y-workshop'

  otlp/collector:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": ${HONEYCOMB_API_KEY}
      "x-honeycomb-dataset": 'otel-collector'

  logging:
    verbosity: detailed

service:
  telemetry:
    metrics:
      level: detailed
      address: '0.0.0.0:8888'
    logs:
      level: "DEBUG"
      development: true
      encoding: "json"
      output_paths:
        - '/logs/collector-debug.log'

  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/logs, logging]

    logs/collector:
      receivers: [ filelog ]
      processors: [ batch ]
      exporters: [otlp/collector]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/metrics, logging]

    metrics/collector:
      receivers: [prometheus]
      processors: [batch]
      exporters: [otlp/collector]

    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlp/traces, logging]
