receivers:
  zipkin:
   
  otlp:
    protocols:
      grpc: # on port 4317
      http: # on port 4318
processors:
  batch:

extensions:
  health_check: # on port 13133
    endpoint: "0.0.0.0:13133"
    check_collector_pipeline:
      enabled: true
      interval: "5m"
      exporter_failure_threshold: 5
  zpages:
    endpoint: :55679

exporters:
  logging:
    logLevel: debug
  

  zipkin/traces:
    endpoint: "http://zipkin:9411/api/v2/spans"

  otlp/traces:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": ${HONEYCOMB_API_KEY}
      "x-honeycomb-dataset": ${HONEYCOMB_DATASET_NAME}
    

service:
  extensions: [zpages, health_check]
  pipelines:
    traces:
      receivers: [zipkin, otlp]
      processors: [batch]
      exporters: [otlp/traces, zipkin/traces, logging]